name: TalkOn
description: Aplicativo de chat em tempo real com Flutter e Supabase

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.10.3  # Versão que você já estava usando
  provider: ^6.1.1
  image_picker: ^1.0.4
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  app_links: ^7.0.0
  characters: ^1.4.1
  material_color_utilities: ^0.13.0
  meta: ^1.17.0
  test_api: ^0.7.8

flutter:
  uses-material-design: true
  assets:
    - assets/logos/

    